TV_SHOWS = [
{"TV Show":"Full House","Network":"ABC ","Year Released":1987},
{"TV Show":"A Different World","Network":"NBC","Year Released":1987},
{"TV Show":"Friends","Network":"NBC","Year Released":1994},
{"TV Show":"The Brady Bunch","Network":"ABC","Year Released":1969},
{"TV Show":"Scrubs","Network":"ABC,NBC","Year Released":2001},
{"TV Show":"Seinfield","Network":"NBC","Year Released":1989},
{"TV Show":"Law and Order: Special Victims Unit","Network":"NBC","Year Released":1999},
{"TV Show":"Sesame Street","Network":"PBS","Year Released":1969},
{"TV Show":"Saved by the Bell","Network":"NBC","Year Released":1989},
{"TV Show":"House","Network":"FOX","Year Released":2004},
{"TV Show":"How I Met Your Mother","Network":"CBS","Year Released":2005},
{"TV Show":"The Fresh Prince of Bel-Air","Network":"NBC","Year Released":1990},
{"TV Show":"Gilmore Girls","Network":"WB","Year Released":2000},
{"TV Show":"Frasier","Network":"NBC","Year Released":1993},
{"TV Show":"Friday Night Lights","Network":"NBC","Year Released":2006},
{"TV Show":"Star Trek","Network":"NBC","Year Released":1966},
{"TV Show":"Will & Grace","Network":"NBC","Year Released":1998},
{"TV Show":"The Simpsons","Network":"FOX","Year Released":1989},
{"TV Show":"I Love Lucy","Network":"CBS","Year Released":1951}]